# Generated by Django 5.0.7 on 2024-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Preparing'), ('2', 'Out for delivery'), ('3', 'Delivered')], max_length=10),
        ),
    ]
