# Generated by Django 5.0.7 on 2024-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='images/foods/default.png', upload_to='images/foods/'),
        ),
    ]
