# Generated by Django 5.0.7 on 2024-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_fooditem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(default='images/food_types/default.png', upload_to='images/food_types/'),
        ),
    ]
